### ISSUE TITLE
Update GeoServer to 2.19.0

### ISSUE THREAD

**Issue by jswk** [cyfronet-fid/docker-geoserver#9]
https://geoserver.org/announcements/2021/03/22/geoserver-2-19-0-released.html

Make sure the S3Geotiff works as intended, as COG support was extended between 2.18 and 2.19. Consider also upgrading to the new COG support (may improve rendering performance).

**Comment by jswk** [comment]
Updating to 2.19.1 yields the following stacktraces:
```
ESC[36mgeoserver_1    |ESC[0m 28 May 11:39:45 WARN [io.imageio] - Unable to create a Reader for: mailto://local-dataset-1/Sentinel-5P_WM/2020-09-03/S5P_NRTI_L2__O3_____20200903T115909_20200903T120409_14983_01_020103_20200903T125146.tif.ovr
ESC[36mgeoserver_1    |ESC[0m com.amazonaws.services.s3.model.AmazonS3Exception: Not Found (Service: Amazon S3; Status Code: 404; Error Code: 404 Not Found; Request ID: 1683381C5C10CB2D; S3 Extended Request ID: null), S3 Extended Request ID: null
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1640)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1058)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4368)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4315)
ESC[36mgeoserver_1    |ESC[0m   at com.amazonaws.services.s3.AmazonS3Client.getObjectMetadata(AmazonS3Client.java:1271)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.s3.S3ImageInputStreamImpl.<init>(S3ImageInputStreamImpl.java:75)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.s3.S3ImageInputStreamImplSpi.createInputStreamInstance(S3ImageInputStreamImplSpi.java:107)
ESC[36mgeoserver_1    |ESC[0m   at it.geosolutions.imageio.core.SourceSPIProvider.getStream(SourceSPIProvider.java:96)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.externalOverviewsCheck(MaskOverviewProvider.java:280)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:153)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.coverage.grid.io.imageio.MaskOverviewProvider.<init>(MaskOverviewProvider.java:129)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.DefaultGranuleAccessProvider.getMaskOverviewsProvider(DefaultGranuleAccessProvider.java:101)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.GranuleDescriptor.init(GranuleDescriptor.java:413)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.GranuleDescriptor.<init>(GranuleDescriptor.java:879)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.catalog.CachingDataStoreGranuleCatalog.getGranuleDescriptor(CachingDataStoreGranuleCatalog.java:207)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.catalog.CachingDataStoreGranuleCatalog.getGranuleDescriptors(CachingDataStoreGranuleCatalog.java:172)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.RasterManager.getGranuleDescriptors(RasterManager.java:1336)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.RasterLayerResponse.prepareResponse(RasterLayerResponse.java:672)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.RasterLayerResponse.processRequest(RasterLayerResponse.java:605)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.RasterLayerResponse.createResponse(RasterLayerResponse.java:573)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.RasterManager.read(RasterManager.java:1327)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.ImageMosaicReader.read(ImageMosaicReader.java:652)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.ImageMosaicReader.read(ImageMosaicReader.java:633)
ESC[36mgeoserver_1    |ESC[0m   at org.geotools.gce.imagemosaic.ImageMosaicReader.read(ImageMosaicReader.java:568)
ESC[36mgeoserver_1    |ESC[0m   at org.geoserver.catalog.CoverageDimensionCustomizerReader.read(CoverageDimensionCustomizerReader.java:235)
ESC[36mgeoserver_1    |ESC[0m   at org.geoserver.catalog.CoverageDimensionCustomizerReader.read(CoverageDimensionCustomizerReader.java:222)
ESC[36mgeoserver_1    |ESC[0m   at org.geoserver.wms.map.RenderedImageMapOutputFormat.readBestCoverage(RenderedImageMapOutputFormat.java:1663)
```
